### ISSUE TITLE
Please change the way you encourage people to install your project.

### ISSUE THREAD

**Issue by Qix-** [Nameles-Org/Nameles#4]
Combinations of `wget`/`curl` and `chmod +x` followed by running things are how malware gets spread and how even honest users get nasty things on their systems.

_Please_ bundle your application properly and distribute it correctly - encouraging the whole `curl | bash` or `wget && chmod +x` workflow is both dangerous and irresponsible.

Thank you <3

**Comment by mikkokotila** [comment]
Thanks @Qix- we shall prioritize this. If you look at the [setup script](https://github.com/Nameles-Org/Nameles/blob/master/setup), what do you suggest in terms of bundling / distribution to best achieve the same. I think there were some struggles we experienced in this respect, but @apastor can share more about that. 

Better yet, do you have bandwidth / interest to make a PR for something that you would recommend in this case? Naturally the objective is to: 

- minimize the commands required to deploy 
- maximize flexibility in terms of Ubuntu/Debian versions 

Thanks a lot for pointing this out. Much appreciated!

**Comment by Qix-** [comment]
Sure - to be clear, I wasn't saying you were packaging malware, but instead that the workflow itself is seen as simple and easy and thus others mimic it, encouraging users to accept such means of installation - which ultimately causes the problems :)

Really, it's less about wget and curl and more about encouraging people to clone the source themselves and inspect/run the scripts inside of the repository. With cloning a Git repository, you have more assurance that scripts haven't been modified over the wire and can verify commit hashes against those on the remote (e.g. Github) to make sure they are indeed the correct scripts.

I'm sure others can point out many more security pitfalls with the `curl|bash` installation method :)

That change only _really_ requires a documentation and verbiage modification in the readme. Otherwise, you can bundle/distribute more official binaries - but I'm not entirely familiar with this project, only with that portion of the readme, so I'm not sure how much help I'd be in that regard.

Thanks for such a prompt response @mikkokotila!

**Comment by apastor** [comment]
Thanks @Qix- for pointing this out. The setup script was done with the best intention to minimize the commands required for running the containers, but you are right in your comments. I can only say that the `curl` and `chmod +x` commands are extracted from the [official installation instructions for docker-compose](https://docs.docker.com/compose/install/). We can install docker-compose with pip as an alternative.

I agree with you too that the setup script should not run the containers. It can be provided to facilitate the installation of docker and docker-compose and maybe print some messages with instructions to run the containers.

What do you think?

**Comment by mikkokotila** [comment]
I don't think the docker-compose part is the problem here ;) @apastor can you explain the issues you faced in trying to create a proper Linux package and I will look into doing it properly later this week. The installation should work without failures from apt-get install. Feel free to create a new issue for the packaging, and I will work on it. Thanks.

**Comment by mikkokotila** [comment]
I removed the last comment as the substance was related with the [Nameles-logfile](https://github.com/Nameles-Org/Nameles-logfile/issues/10) repo.
